### ISSUE TITLE
[Feature Request] Add 'remember me' option

### ISSUE THREAD

**Issue by ArthurGarnier** [turtl/mobile#12]
Enter your login each time you want to access to your notes it's a bit annoying. ;)

It's a bit linked with : https://github.com/turtl/mobile/issues/9

**Comment by orthecreedence** [comment]
https://trello.com/c/Bs4NPtgE

^ This is actively being worked on, and is one of the highest priorities for the next release.

**Comment by JonasDralle** [comment]
why is this closed when it's not fixed?
do you guys close issues when you acknowledge them instead of when you have finished them?

a bit confusing for me... but I won't hinder you

**Comment by orthecreedence** [comment]
Jonas, the reason this is closed is because we track our issues on Trello, not github. Trello is much easier for me to manage, so I usually end up moving all open issues to Trello and closing them in Github. I close it in Github so I don't have to manage it in two places =]

**Comment by JonasDralle** [comment]
makes sense
