### ISSUE TITLE
Adding Turtl to F-Droid

### ISSUE THREAD

**Issue by YogliB** [turtl/mobile#13]
It would be awesome if we could find the Turtl app for android on F-Droid, so we won't need Google Play in order to use it and be up to date.

**Comment by orthecreedence** [comment]
Agreed, it would be awesome. It's currently in the submission queue: https://f-droid.org/forums/topic/turtl/

Please feel free to bump the post!

**Comment by cavebeat** [comment]
Hi,

I have recreated the forumpost. Pls reopen this issue here.

https://forum.f-droid.org/t/adding-turtl-to-f-droid-repo/1507

**Comment by cavebeat** [comment]
I've created a new Request for Package on F-Droid/Gitlab, please reopen @orthecreedence this issue . 
https://gitlab.com/fdroid/rfp/issues/412

**Comment by orthecreedence** [comment]
So apparently xwalk is now deprecated, which means Turtl should (hopefully) run without it, I guess? So, hello f-droid in the new release (v0.7). Thanks @cavebeat for opening the request.

I still have a lot of work to do on the v0.7 release, but I'll babysit the f-droid entry. Would love to finally get Turtl on there.
