### ISSUE TITLE
Feature request: easy login for smartphones

### ISSUE THREAD

**Issue by JonasDralle** [turtl/mobile#14]
I really love that you guys take security serious and it's great that you autologout when I close the app

still one problem remains: I used my email adress as login and my password is fairly long and strong. Thus when I need to access my notes I'll have to type all that stuff to get to them. This can easily take 30 seconds or so and is an absolute flow buster.

I know this would lower security but what if you add an settings option to enable "quick login" which would basically mean that some auth token or something will be permanently stored on my device and it will be unlocked with a pin dial.
Thus my password is saved nowhere but rather some token instead and this one is secured with a short pin which I can easily type and thus gain quick access to my notes.

This should be an optional way for people to login because some of the already existing users might want to keep the current login method. When they don't want it they can ignore the on/off switch in settings or just disable it.

When you guys think this is a too big security hole maybe add a feature that we can create low-security boards which will have this feature. So I can have a board "shopping lists" which is securely encrypted like everything else but only requires a speed login.

I really would appreciate this :)

Have a good day ; stay awesome

**Comment by JonasDralle** [comment]
oh sorry I think this was already suggested in #9 and #12
Sorry for the duplicate :P

**Comment by orthecreedence** [comment]
Hi Jonas! This is a hard problem to solve, but we are working very hard to resolve it. Basically we need to build a service that runs separately from the app itself and stores the password such that only the Turtl app can access it. It's tricky, but luckily others have done this and we just need to follow in their footsteps. This is tracked here if you want to follow it: https://trello.com/c/Bs4NPtgE

(Closing this issue in favor of the Trello item)

**Comment by JonasDralle** [comment]
only maniacs store password

only store the encrypted stuff. When the correct user/pass is entered it will generate the correct key which will unlock the stuff. I assume you are using password derivation
when you have the correct key you can access it. When not then you have no way of finding it out by analysing the encrypted block.

of course bruteforcing is easier when it's stored offline but when you use PBKDF2 and AES properly then this should be no problem (or whatever algorithm you use)
