### ISSUE TITLE
Dark/black mode for OLED displays

### ISSUE THREAD

**Issue by sojusnik** [turtl/mobile#3]
Users with OLED displays (and to a smaller extent all other display types) would greatly benefit from a dark or black mode/theme on Android in terms of battery endurance.

**Comment by orthecreedence** [comment]
That's an interesting idea. I didn't know this actually helped with battery life. Does this work best with true black (#000000)? Could be fun to have a "hacker mode" in Turtl for late night authoring and battery saving. 

https://trello.com/c/XQPiYeuC

**Comment by sojusnik** [comment]
Yes, it must be true black. The battery savings are significant on OLED displays, don't know about other types.
