### ISSUE TITLE
[Feature request] Improve Android app

### ISSUE THREAD

**Issue by Primokorn** [turtl/mobile#8]
Hi,
It would be nice to have Material Design and to improve the overall performance of Turtl.
In addition, could you add an option to remember our login at start and reminders to notes?

Thank you.

**Comment by orthecreedence** [comment]
As far as remembering login, this is something I'm actively working on, but it's very difficult to do securely: https://trello.com/c/Bs4NPtgE

I've had many requests to implement material design. However, when redesigning Turtl this past year, I closely followed Google's material design guide very closely. Can you give a bit more detail into what aspects of material design Turtl is missing? I would love your feedback here.

**Comment by Primokorn** [comment]
Actually the performance is more important than Material design.
There's a documentation from Google about Material design [here](https://www.google.com/design/spec/material-design/introduction.html#).
[Resizer](https://design.google.com/) may help you to implement it.

**Comment by rubbingalcoholic** [comment]
owl

**Comment by orthecreedence** [comment]
![](http://i.imgur.com/t4P2IuL.jpg)

#harrrr

**Comment by Primokorn** [comment]
Why did you close it???

**Comment by orthecreedence** [comment]
Our main issue tracker is here: https://trello.com/b/yIQGkHia/turtl-product-dev

I close all issues on here after tracking them in Trello =]
